name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare Mock Data & Directories
      run: |
        mkdir -p data models results
        echo "id,gene_1,gene_2" > data/data.csv
        echo "1,1.0,2.0" >> data/data.csv
        echo "2,5.0,2.0" >> data/data.csv
        echo "id,label" > data/labels.csv
        echo "1,BRCA" >> data/labels.csv
        echo "2,LUAD" >> data/labels.csv

    - name: Run Tests
      run: |
        pytest tests/ --html=report.html --self-contained-html

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
